/**
 * PDF Export Script for Emirates Rawabi Pre-Discovery Report
 * Uses Puppeteer to capture all slides with full CSS styling
 * Generated by NXSYS Presentation Generator
 *
 * Usage: npm run export-pdf
 * Output: emirates-rawabi-pre-discovery-report.pdf
 */

const puppeteer = require('puppeteer');
const { PDFDocument } = require('pdf-lib');
const fs = require('fs');
const path = require('path');

const CONFIG = {
    totalSlides: 40,
    viewportWidth: 1920,
    viewportHeight: 1080,
    outputFile: 'Emirates-Rawabi-SAP-Pre-Discovery.pdf',
    slideTransitionWait: 400,
};

async function exportToPDF() {
    console.log('\n========================================');
    console.log('  Emirates Rawabi Pre-Discovery Report');
    console.log('  PDF Export');
    console.log('========================================\n');

    let browser = null;

    try {
        // Launch browser
        console.log('Launching browser...');
        browser = await puppeteer.launch({
            headless: 'new',
            args: [
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-web-security',
                '--allow-file-access-from-files',
                '--font-render-hinting=none',
            ]
        });

        const page = await browser.newPage();

        // Set viewport to full HD for best quality
        await page.setViewport({
            width: CONFIG.viewportWidth,
            height: CONFIG.viewportHeight,
            deviceScaleFactor: 2, // High DPI for crisp text
        });

        // Navigate to presentation using file:// protocol
        const filePath = path.join(__dirname, 'index.html');
        const fileUrl = `file:///${filePath.replace(/\\/g, '/')}`;
        console.log('Loading presentation from:', fileUrl);

        await page.goto(fileUrl, {
            waitUntil: 'networkidle2',
            timeout: 60000
        });

        // Wait for page to fully load
        console.log('Waiting for page to load...');
        await new Promise(r => setTimeout(r, 5000));

        // Check if slides exist and count them
        const slideCount = await page.evaluate(() => {
            return document.querySelectorAll('.slide').length;
        });
        console.log(`Found ${slideCount} slides`);

        if (slideCount === 0) {
            throw new Error('No slides found in the presentation');
        }

        // Setup for PDF export - hide UI and prepare slides
        console.log('Preparing for export...');
        await page.evaluate(() => {
            // Hide preloader
            const preloader = document.getElementById('preloader');
            if (preloader) {
                preloader.style.display = 'none';
                preloader.style.visibility = 'hidden';
            }

            // Hide UI elements that shouldn't be in PDF
            const elementsToHide = [
                '.progress-bar',
                '.slide-counter',
                '.nav-arrows',
                '.slide-indicators',
                '.slide-titles-nav',
                '.presenter-notes',
                '.preloader',
                '.download-buttons',
                '.finding-detail-panel',
                '.panel-overlay',
                '.export-modal'
            ];
            elementsToHide.forEach(selector => {
                document.querySelectorAll(selector).forEach(el => {
                    el.style.display = 'none';
                    el.style.visibility = 'hidden';
                });
            });

            // Adjust presentation to full width
            const presentation = document.querySelector('.presentation');
            if (presentation) {
                presentation.style.marginLeft = '0';
                presentation.style.width = '100%';
                presentation.style.left = '0';
            }

            // Make all slides take full width and position correctly
            document.querySelectorAll('.slide').forEach(slide => {
                slide.style.left = '0';
                slide.style.width = '100%';
            });

            // Adjust slide content for full width
            document.querySelectorAll('.slide-content').forEach(content => {
                content.style.marginLeft = 'auto';
                content.style.marginRight = 'auto';
                content.style.paddingLeft = '80px';
                content.style.paddingRight = '80px';
            });
        });

        // Create temp directory for slide PDFs
        const tempDir = path.join(__dirname, 'temp-slides');
        if (!fs.existsSync(tempDir)) {
            fs.mkdirSync(tempDir);
        }

        // Capture each slide
        const totalSlides = Math.min(slideCount, CONFIG.totalSlides);
        console.log(`\nCapturing ${totalSlides} slides...\n`);

        for (let i = 0; i < totalSlides; i++) {
            // Navigate to slide using direct DOM manipulation
            await page.evaluate((slideIndex) => {
                const slides = document.querySelectorAll('.slide');

                // Update slide classes for visibility
                slides.forEach((slide, idx) => {
                    slide.classList.remove('active', 'prev', 'next');
                    if (idx < slideIndex) {
                        slide.classList.add('prev');
                    } else if (idx > slideIndex) {
                        slide.classList.add('next');
                    }
                });
                slides[slideIndex].classList.add('active');

                // Set counter values immediately (skip animation)
                const counters = slides[slideIndex].querySelectorAll('[data-count]');
                counters.forEach(counter => {
                    const target = parseInt(counter.dataset.count);
                    counter.textContent = target.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
                });
            }, i);

            // Wait for slide transition
            await new Promise(r => setTimeout(r, CONFIG.slideTransitionWait));

            // Generate PDF for this slide
            const slidePdf = await page.pdf({
                width: `${CONFIG.viewportWidth}px`,
                height: `${CONFIG.viewportHeight}px`,
                printBackground: true,
                preferCSSPageSize: false,
                margin: { top: 0, right: 0, bottom: 0, left: 0 },
            });

            // Save individual slide PDF
            const slideFile = path.join(tempDir, `slide-${String(i).padStart(2, '0')}.pdf`);
            fs.writeFileSync(slideFile, slidePdf);

            const progress = Math.round(((i + 1) / totalSlides) * 100);
            const progressBar = '='.repeat(Math.floor(progress / 5)) + ' '.repeat(20 - Math.floor(progress / 5));
            process.stdout.write(`\r  [${progressBar}] ${progress}% - Slide ${i + 1}/${totalSlides}`);
        }

        console.log('\n\nMerging slides into single PDF...');

        // Merge all slide PDFs
        const mergedPdf = await PDFDocument.create();

        for (let i = 0; i < totalSlides; i++) {
            const slideFile = path.join(tempDir, `slide-${String(i).padStart(2, '0')}.pdf`);
            const slideBytes = fs.readFileSync(slideFile);
            const slidePdf = await PDFDocument.load(slideBytes);
            const [page] = await mergedPdf.copyPages(slidePdf, [0]);
            mergedPdf.addPage(page);
        }

        // Save merged PDF
        const outputPath = path.join(__dirname, CONFIG.outputFile);
        const mergedBytes = await mergedPdf.save();
        fs.writeFileSync(outputPath, mergedBytes);

        // Cleanup temp files
        console.log('Cleaning up temporary files...');
        for (let i = 0; i < totalSlides; i++) {
            const slideFile = path.join(tempDir, `slide-${String(i).padStart(2, '0')}.pdf`);
            if (fs.existsSync(slideFile)) {
                fs.unlinkSync(slideFile);
            }
        }
        fs.rmdirSync(tempDir);

        console.log('\n========================================');
        console.log('  PDF Export Complete!');
        console.log('========================================');
        console.log(`\n  Output: ${outputPath}`);
        console.log(`  Slides: ${totalSlides}`);
        console.log(`  Size: ${(mergedBytes.length / 1024 / 1024).toFixed(2)} MB\n`);

    } catch (error) {
        console.error('\nError during PDF export:', error);
        throw error;
    } finally {
        // Cleanup
        if (browser) {
            await browser.close();
        }
    }
}

// Run export
exportToPDF().catch(error => {
    console.error('Export failed:', error);
    process.exit(1);
});
