// All Findings Data from Deep-Dive Analysis
const findingsData = [
    { id: 1, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Demand Planning", observation: "Al Rawabi plans production based on 'liters of milk' rather than milk components (Fat, Protein, Lactose). This is a FUNDAMENTAL FLAW. In dairy manufacturing, what you sell is Fat and Protein - milk is merely the carrier.", criticality: "High" },
    { id: 2, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Demand Planning", observation: "All production planning - demand forecasting, milk balancing, fat allocation, scheduling - is performed in Excel spreadsheets maintained by individuals. SAP is bypassed for the most critical planning decisions.", criticality: "High" },
    { id: 3, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Demand Planning", observation: "Sales team creates weekly forecasts manually and submits directly to production. No statistical tools, no MAPE/Bias tracking, no connection to actual demand.", criticality: "High" },
    { id: 4, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Recipe Mgmt", observation: "BOMs list 'Milk' as an ingredient with fixed quantity. They do NOT decompose milk into Fat grams, Protein grams, and Lactose grams - which is how dairy ACTUALLY works.", criticality: "High" },
    { id: 5, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Recipe Mgmt", observation: "Frequent recipe changes happen on the floor to 'keep the show running' - adjusting fat content, changing protein sources, substituting ingredients. These changes are NOT reflected in SAP BOMs.", criticality: "High" },
    { id: 6, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Recipe Mgmt", observation: "When milk is separated, you get BOTH cream AND skim milk - these are co-products with independent value. SAP is not configured to handle co-product output or value allocation.", criticality: "High" },
    { id: 7, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "MRP", observation: "A dedicated person manages the daily fat balance in Excel - tracking incoming milk fat content, calculating cream separation requirements, allocating fat across products. This happens entirely outside SAP.", criticality: "High" },
    { id: 8, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "MRP", observation: "Raw milk from farms varies daily in fat content (3.0% to 4.5%), protein (2.8% to 3.6%), and SNF. This variability is known to the lab but NOT captured in SAP.", criticality: "High" },
    { id: 9, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "MRP", observation: "After separation, cream goes to one silo, skim to another. But SAP inventory still shows 'Raw Milk' - not the separated components.", criticality: "High" },
    { id: 10, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Scheduling", observation: "The production manager manually converts planned orders to production orders ONE BY ONE - spending half of every day on scheduling instead of managing production.", criticality: "High" },
    { id: 11, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Scheduling", observation: "'Capacity planning is something which is not there' - explicitly confirmed during workshop. MRP generates planned orders assuming infinite capacity.", criticality: "High" },
    { id: 12, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Scheduling", observation: "Al Rawabi produces 120 SKUs daily, all fresh products requiring same-day production. This complexity is managed manually without any system optimization.", criticality: "High" },
    { id: 13, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Milk Reception", observation: "When milk tankers arrive, lab tests measure fat%, protein%, SNF, acidity, temperature. These results are recorded ON PAPER only. SAP receives the milk as 'X liters of Raw Milk'.", criticality: "High" },
    { id: 14, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Milk Reception", observation: "Physical weighbridge exists but operates independently. Weight is recorded manually. Gate pass system is for visitors only.", criticality: "High" },
    { id: 15, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Milk Reception", observation: "Physical production continues even when SAP receipts are delayed or blocked. Instance documented of 22 days of production running without proper goods receipts in SAP.", criticality: "High" },
    { id: 16, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Standardization", observation: "Current SAP configuration does not support variable-yield processes, co-products, or component-based planning required in dairy manufacturing.", criticality: "High" },
    { id: 17, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Standardization", observation: "Critical food safety parameters exist on the shop floor but this data is NOT captured in SAP - only exists on paper charts or PLC historians.", criticality: "High" },
    { id: 18, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Standardization", observation: "Every dairy must reconcile: Milk In = Products Out + Process Loss + Cream/Skim Balance. This daily mass balance is done in EXCEL, not SAP.", criticality: "High" },
    { id: 19, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Quality Mgmt", observation: "'SAP QM is not active' - explicitly confirmed. All quality testing is recorded on PAPER and filed by date.", criticality: "High" },
    { id: 20, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Quality Mgmt", observation: "Products are released to unrestricted stock and shipped BEFORE final test results. Direct quote: 'We sleep with that risk.'", criticality: "High" },
    { id: 21, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Quality Mgmt", observation: "Food safety regulations require ability to trace finished product back to raw material source within 4 hours. Current system cannot do this.", criticality: "High" },
    { id: 22, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Traceability", observation: "Traceability chain is BROKEN in SAP. Supplier batch numbers often missing at goods receipt. Production orders don't link to input batches.", criticality: "High" },
    { id: 23, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Traceability", observation: "The only complete traceability exists in paper files. To trace a product, someone must physically retrieve and cross-reference multiple paper files.", criticality: "High" },
    { id: 24, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Traceability", observation: "Since milk components are not tracked separately, there is no way to trace which supplier's FAT ended up in which product.", criticality: "High" },
    { id: 25, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Inventory", observation: "Production cost visibility is MONTHLY, not daily. Actual costs are calculated at month-end through variance analysis.", criticality: "High" },
    { id: 26, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Inventory", observation: "Since milk is not tracked by components, product costs are calculated using 'average milk cost' regardless of actual fat/protein content.", criticality: "High" },
    { id: 27, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Inventory", observation: "At month-end, massive production variances appear because daily component balancing was done in Excel.", criticality: "High" },
    { id: 28, entity: "Al Rawabi Dairy Company", module: "Production Planning", process: "Inventory", observation: "Fat is the most valuable milk component. Daily fat losses are not quantified. The value of 'missing fat' is buried in general production variance.", criticality: "High" },
    { id: 29, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Van Sales & Routes", observation: "SAP has no visibility of individual van inventory. All 300+ routes invisible to SAP, only DC-level stock known.", criticality: "High" },
    { id: 30, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Van Sales & Routes", observation: "Devices operate in offline mode all day with morning/evening sync only. Real-time visibility of van activities not available.", criticality: "High" },
    { id: 31, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Van Sales & Routes", observation: "Ransale back-office is the operational brain; SAP is peripheral. All pricing, promotions, credit, returns, and route management happen outside SAP.", criticality: "High" },
    { id: 32, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Van Sales & Routes", observation: "RoadNet route optimization temporarily stopped due to master data quality issues.", criticality: "Medium" },
    { id: 33, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Order Mgmt", observation: "60-70% of sales are 'pull' orders collected via phone, email, WhatsApp - none systematically recorded.", criticality: "High" },
    { id: 34, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Order Mgmt", observation: "Van sales uses direct billing without SAP delivery notes. Custom movement types used instead of standard delivery-based goods movement.", criticality: "High" },
    { id: 35, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Order Mgmt", observation: "SAP sales orders created from van sales data upload AFTER sale completion, not from customer request.", criticality: "Medium" },
    { id: 36, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Order Mgmt", observation: "Van sales is not operating as an order fulfillment tool. True order fulfillment exists only for e-commerce channel.", criticality: "Medium" },
    { id: 37, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Pricing", observation: "All pricing logic in Ransale back-office, not SAP. Creates dual maintenance and potential sync issues.", criticality: "Medium" },
    { id: 38, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Pricing", observation: "Promotion effectiveness tracking happens in back-office only. SAP has no visibility of promotion performance.", criticality: "Medium" },
    { id: 39, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Pricing", observation: "Promotion budgets not controlled through SAP. Finance visibility of promotion spending is indirect.", criticality: "Low" },
    { id: 40, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Returns", observation: "Returns captured in van sales but quality analysis not flowing to SAP QM. QM module not active for returns inspection.", criticality: "High" },
    { id: 41, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Returns", observation: "Detailed return reasons captured at point of return in Ransale but SAP receives only summary transactions.", criticality: "Medium" },
    { id: 42, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Returns", observation: "Practice of differentiated near-expiry pricing stopped due to lack of physical control.", criticality: "Medium" },
    { id: 43, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Returns", observation: "Return rates tracked but no formal return reduction initiative with customer-level analysis.", criticality: "Low" },
    { id: 44, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Credit Mgmt", observation: "Credit check happens in van sales system. SAP knows credit position only after end-of-day posting.", criticality: "Medium" },
    { id: 45, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Credit Mgmt", observation: "Cash collection, reconciliation, and deposit tracking managed in back-office. SAP receives summarized cash transactions only.", criticality: "Medium" },
    { id: 46, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Credit Mgmt", observation: "Head office vs branch office invoicing and credit management for multi-location customers not fully clarified.", criticality: "Low" },
    { id: 47, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Shelf-Life", observation: "Shelf-life visible in van sales but system-enforced FEFO unclear. Risk of shipping older stock.", criticality: "High" },
    { id: 48, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Shelf-Life", observation: "Major retailers require minimum remaining shelf-life. No evidence this is checked in system during allocation.", criticality: "High" },
    { id: 49, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Shelf-Life", observation: "SAP not used for order promising with shelf-life consideration.", criticality: "Medium" },
    { id: 50, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Shelf-Life", observation: "Near-expiry stock management stopped. No systematic alternate channel for disposal.", criticality: "Medium" },
    { id: 51, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "E-Commerce", observation: "Magento orders manually consolidated and posted to van sales as internal customer. No real-time inventory sync.", criticality: "High" },
    { id: 52, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "E-Commerce", observation: "Coordinator manually collates orders from Magento and creates single order in van sales. Process is labor-intensive.", criticality: "High" },
    { id: 53, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "E-Commerce", observation: "Talabat dark store stock requests may not come to SAP. Identified as auditable concern.", criticality: "Medium" },
    { id: 54, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "E-Commerce", observation: "E-commerce sales posted as internal customer. True e-commerce profitability not visible in SAP.", criticality: "Medium" },
    { id: 55, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "SAP Integration", observation: "All transactions posted to SAP at end of day in batch. Real-time stock visibility not available during business hours.", criticality: "High" },
    { id: 56, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "SAP Integration", observation: "Stock transferred between locations may show in transit but 'SAP has no clue.' Identified as auditable issue.", criticality: "High" },
    { id: 57, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "SAP Integration", observation: "Custom movement types and direct billing without delivery document. Standard Order-Delivery-Billing flow not followed.", criticality: "Medium" },
    { id: 58, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "SAP Integration", observation: "Master data flows SAP to Van Sales only. Customer/material changes in van sales not reflected back.", criticality: "Low" },
    { id: 59, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Revenue", observation: "Routes not defined in SAP means route-level profitability cannot be calculated.", criticality: "High" },
    { id: 60, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Revenue", observation: "Retail POS sales consolidated as single transaction. Potential FTA compliance risk.", criticality: "High" },
    { id: 61, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Revenue", observation: "E-commerce, B2B van sales, retail POS all posted without clear channel identification.", criticality: "Medium" },
    { id: 62, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Revenue", observation: "All KPIs, driver performance, route efficiency tracked in Ransale back-office. SAP provides only financial posting.", criticality: "Medium" },
    { id: 63, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Crates", observation: "All crate tracking, reconciliation, and customer balances managed in Ransale. SAP has no visibility.", criticality: "Medium" },
    { id: 64, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Crates", observation: "Crate deposits and refunds not tracked as financial transactions in SAP.", criticality: "Medium" },
    { id: 65, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Crates", observation: "Asset management feature available in Ransale but operation is very limited. Upgrade planned.", criticality: "Low" },
    { id: 66, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Delivery", observation: "Temperature compliance managed operationally but not integrated with SAP.", criticality: "Medium" },
    { id: 67, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Delivery", observation: "RoadNet route optimization temporarily stopped. Manual journey planning in use.", criticality: "Medium" },
    { id: 68, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Delivery", observation: "Customer delivery windows likely managed through route sequencing but not explicitly tracked.", criticality: "Low" },
    { id: 69, entity: "Al Rawabi Dairy Company", module: "Sales & Distribution", process: "Delivery", observation: "Proof of delivery exists in device but integration with SAP for dispute resolution not confirmed.", criticality: "Low" },
    { id: 70, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Group Structure", observation: "Company codes use different numbering conventions. No standardized naming.", criticality: "High" },
    { id: 71, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Group Structure", observation: "New Kizad manufacturing entity being established. Integration planning required.", criticality: "High" },
    { id: 72, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Group Structure", observation: "Oman operates in OMR, Sudan in USD. Different currency and tax considerations.", criticality: "Medium" },
    { id: 73, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Chart of Accounts", observation: "Greenfield has separate COA from other entities. Creates consolidation complexity.", criticality: "High" },
    { id: 74, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Chart of Accounts", observation: "Same material may have different codes across companies. No global material master.", criticality: "High" },
    { id: 75, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Chart of Accounts", observation: "Different numbering conventions across entities. Goal to standardize not yet achieved.", criticality: "High" },
    { id: 76, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Consolidation", observation: "Consolidation performed using Excel with trial balances aggregated manually.", criticality: "High" },
    { id: 77, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Consolidation", observation: "IC identification and elimination is manual. Requires meticulous groundwork.", criticality: "High" },
    { id: 78, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Consolidation", observation: "SAP Group Reporting not implemented. Cannot drill down from consolidated to transaction level.", criticality: "High" },
    { id: 79, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Intercompany", observation: "Intercompany transactions processed as regular buyer-supplier transactions. Not automated.", criticality: "High" },
    { id: 80, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Intercompany", observation: "No transfer pricing between entities. UAE corporate tax now requires documentation.", criticality: "High" },
    { id: 81, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Intercompany", observation: "Invoices generated manually for VAT compliance. Not automated.", criticality: "High" },
    { id: 82, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Cost Centers", observation: "Cost centers specific to each company code. Cross-company reporting requires aggregation.", criticality: "Medium" },
    { id: 83, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Cost Centers", observation: "No statistical key figures for allocation. Activity-based allocation not fully utilized.", criticality: "Medium" },
    { id: 84, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Cost Centers", observation: "Single cost center hierarchy with holding at top. Standard structure but governance needed.", criticality: "Low" },
    { id: 85, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Profit Centers", observation: "Large number of profit centers (35) across segments and DCs. Maintenance needed.", criticality: "Medium" },
    { id: 86, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Profit Centers", observation: "Document splitting may be active but needs confirmation. Required for profit center balance sheets.", criticality: "High" },
    { id: 87, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Profit Centers", observation: "Authorization based on profit/cost centers. Dairy vs Poultry team visibility managed this way.", criticality: "Medium" },
    { id: 88, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Product Costing", observation: "Actual costing run monthly to allocate overheads. Material ledger active with cost component split.", criticality: "Medium" },
    { id: 89, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Product Costing", observation: "Livestock treated as inventory, revalued at year-end. Not IAS 41 compliant biological asset accounting.", criticality: "High" },
    { id: 90, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "Product Costing", observation: "Material, Labor, Depreciation, Maintenance, Utilities activity types. Fixed rates applied.", criticality: "Medium" },
    { id: 91, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "CO-PA", observation: "CO-PA is costing-based in ECC. S/4HANA migration requires consideration as account-based is standard.", criticality: "High" },
    { id: 92, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "CO-PA", observation: "One operating concern active. Will need account-based migration.", criticality: "High" },
    { id: 93, entity: "Al Rawabi Dairy Company", module: "Finance & Controlling", process: "CO-PA", observation: "Profitability reporting by segment, product, region active. Good foundation for enhancement.", criticality: "Medium" },
    { id: 94, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Demand Planning", observation: "Heavy reliance on Excel for planning calculations. Sales data managed in spreadsheets.", criticality: "High" },
    { id: 95, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Demand Planning", observation: "Forecast data processed through Resa tool before manual upload to SAP as PIRs.", criticality: "High" },
    { id: 96, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Demand Planning", observation: "Rolling forecast went live last week. Remaining weeks from annual budget. Process still maturing.", criticality: "High" },
    { id: 97, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "MRP", observation: "MRP concept in place but not fully operational. Entire process from forecasting to PR creation is manual.", criticality: "High" },
    { id: 98, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "MRP", observation: "All calculations for feed requirements done in Excel by farm personnel.", criticality: "High" },
    { id: 99, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "MRP", observation: "Only initial data extraction from SAP is automated. All calculations and PR creation remain manual.", criticality: "High" },
    { id: 100, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Milk Balancing", observation: "Team uses complex Excel sheet for balancing with formulas for daily operations. Tedious and time-consuming.", criticality: "High" },
    { id: 101, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Milk Balancing", observation: "Balancing done at milk level, not component level (fat/protein/SNF). Fat is critical but not tracked.", criticality: "High" },
    { id: 102, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Milk Balancing", observation: "Current balancing based on monthly requirements but daily operations often inconsistent.", criticality: "High" },
    { id: 103, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Procurement", observation: "Entire process from PR to PO is manual. Create PO from quotation, compare vendors, select, finalize.", criticality: "High" },
    { id: 104, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Procurement", observation: "Manual comparison and vendor evaluation. Buyer experience plays significant role. No vendor scorecards.", criticality: "High" },
    { id: 105, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Procurement", observation: "Contracts being centralized but process remains manual. Expiration monitoring needed.", criticality: "Medium" },
    { id: 106, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Goods Receipt", observation: "Palletization with barcode capture working. HU identifier crucial for tracking items.", criticality: "Medium" },
    { id: 107, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Goods Receipt", observation: "Emergency purchases processed through petty cash (AED 7,000 limit).", criticality: "Medium" },
    { id: 108, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Goods Receipt", observation: "Barcode provides SCA code, Area DC, Batch number, Manufacturing date, Expiry date.", criticality: "Low" },
    { id: 109, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Inventory", observation: "Kizad has no inbound transfers allowed due to biosecurity. Rule not fully system-enforced.", criticality: "High" },
    { id: 110, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Inventory", observation: "Dead stock and consumption issues require attention. Significant task.", criticality: "High" },
    { id: 111, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Inventory", observation: "Stock Transport Orders between DCs operational. Both plant-based and SLOC-based STOs used.", criticality: "Medium" },
    { id: 112, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Warehouse", observation: "No dedicated warehouse manager role. Items can be stored wherever needed.", criticality: "High" },
    { id: 113, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Warehouse", observation: "System handles transfer orders and confirmations but some complexities may be overlooked.", criticality: "High" },
    { id: 114, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Warehouse", observation: "WMS assists in determining storage locations and managing transfer records. Basic functionality.", criticality: "Medium" },
    { id: 115, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Master Data", observation: "Same items have duplicate codes hindering tracking and invoicing.", criticality: "High" },
    { id: 116, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Master Data", observation: "Vendors separate per company code. Duplicate vendors across entities.", criticality: "High" },
    { id: 117, entity: "Al Rawabi Dairy Company", module: "Materials Management", process: "Master Data", observation: "Custom material types defined (e.g., ZROH). Need to evaluate complexity.", criticality: "High" },
    { id: 118, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Product Brands", observation: "Two distinct brands with different temperature requirements. Al Rawdah (fresh, chilled) and Al Salwa (frozen).", criticality: "High" },
    { id: 119, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Product Brands", observation: "B2C fresh goes through van sales, B2B frozen has separate distribution channel.", criticality: "High" },
    { id: 120, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Product Brands", observation: "Brand positioning and pricing strategy not coordinated. Market cannibalization risk.", criticality: "Medium" },
    { id: 121, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Van Sales", observation: "32 routes operated with SONIC handheld devices. Devices operate offline throughout the day.", criticality: "High" },
    { id: 122, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Van Sales", observation: "Real-time stock visibility not available. Van inventory reconciled only at end of day.", criticality: "High" },
    { id: 123, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Van Sales", observation: "Route profitability not visible - all sales aggregate to single cost center.", criticality: "Medium" },
    { id: 124, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Route Profitability", observation: "No CO-PA analysis for route-level profitability. Manual analysis in spreadsheets.", criticality: "High" },
    { id: 125, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Route Profitability", observation: "Cannot identify which routes are profitable vs. which are subsidized.", criticality: "High" },
    { id: 126, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Route Profitability", observation: "Driver performance and delivery efficiency tracked outside SAP.", criticality: "Medium" },
    { id: 127, entity: "Emirates National Foods", module: "Sales & Distribution", process: "B2B Key Accounts", observation: "Nandos and other key accounts require custom marinades with specific specifications.", criticality: "High" },
    { id: 128, entity: "Emirates National Foods", module: "Sales & Distribution", process: "B2B Key Accounts", observation: "Recipe management for customer-specific products not in SAP.", criticality: "Medium" },
    { id: 129, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Export Sales", observation: "Export represents only 3% of frozen sales. Direct SAP orders used for export.", criticality: "High" },
    { id: 130, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Export Sales", observation: "Export documentation and compliance managed manually.", criticality: "High" },
    { id: 131, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Export Sales", observation: "No integrated export planning with production.", criticality: "Medium" },
    { id: 132, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Returns Handling", observation: "13% return rate for fresh products - significantly higher than industry benchmark.", criticality: "High" },
    { id: 133, entity: "Emirates National Foods", module: "Sales & Distribution", process: "Returns Handling", observation: "Good returns are frozen and sold as Al Salwa brand. No value tracking.", criticality: "Medium" },
    { id: 134, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Procurement", observation: "85% eggs from Salwa, 15-16% from open market imports.", criticality: "High" },
    { id: 135, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Procurement", observation: "No formal agreement with external suppliers for quality or pricing.", criticality: "High" },
    { id: 136, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Procurement", observation: "Import planning not integrated with hatchery capacity.", criticality: "Medium" },
    { id: 137, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Grading", observation: "A-grade eggs are hatchable, B-grade rejected. Grading specs newly defined.", criticality: "High" },
    { id: 138, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Grading", observation: "Grading done at ENF, not at source (Salwa). Transportation damage not attributable.", criticality: "High" },
    { id: 139, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Grading", observation: "Rejection rates not analyzed by supplier or flock.", criticality: "Medium" },
    { id: 140, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Storage", observation: "Optimal storage is 7-8 days. Hatchability degrades significantly after 20+ days.", criticality: "High" },
    { id: 141, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Storage", observation: "FIFO for egg setting not system-enforced. Age-based prioritization manual.", criticality: "High" },
    { id: 142, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Egg Storage", observation: "Storage conditions (temperature, humidity) not logged in SAP.", criticality: "High" },
    { id: 143, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Incubation Cycle", observation: "21-day incubation cycle with 200,000 eggs per setting.", criticality: "High" },
    { id: 144, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Incubation Cycle", observation: "Incubation parameters (temperature, humidity, turning) not captured in SAP.", criticality: "High" },
    { id: 145, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Incubation Cycle", observation: "Incubator capacity utilization not tracked systematically.", criticality: "Medium" },
    { id: 146, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Hatchability", observation: "Actual hatchability 90-92% vs estimate of 85-86%. Planning uses conservative estimate.", criticality: "High" },
    { id: 147, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Hatchability", observation: "Hatchability variance not analyzed by egg source or incubator.", criticality: "High" },
    { id: 148, entity: "Emirates National Foods", module: "Hatchery Operations", process: "Hatchability", observation: "No root cause analysis for hatchability failures.", criticality: "High" },
    { id: 149, entity: "Emirates National Foods", module: "Hatchery Operations", process: "DOC Output", observation: "150,000 day-old chick capacity for own farms.", criticality: "High" },
    { id: 150, entity: "Emirates National Foods", module: "Hatchery Operations", process: "DOC Output", observation: "DOC quality grading subjective - no standardized criteria.", criticality: "High" },
    { id: 151, entity: "Emirates National Foods", module: "Hatchery Operations", process: "DOC Output", observation: "Chick allocation to farms based on manual planning.", criticality: "Medium" },
    { id: 152, entity: "Emirates National Foods", module: "Farm Operations", process: "Farm Capacity", observation: "13 farms with 6 houses each, 150,000 birds total capacity.", criticality: "High" },
    { id: 153, entity: "Emirates National Foods", module: "Farm Operations", process: "Farm Capacity", observation: "Farm utilization not optimized - some farms consistently underutilized.", criticality: "High" },
    { id: 154, entity: "Emirates National Foods", module: "Farm Operations", process: "Farm Capacity", observation: "No system visibility of farm-level capacity and availability.", criticality: "High" },
    { id: 155, entity: "Emirates National Foods", module: "Farm Operations", process: "DOC Placement", observation: "One production order per house for 35-42 day growing cycle.", criticality: "High" },
    { id: 156, entity: "Emirates National Foods", module: "Farm Operations", process: "DOC Placement", observation: "Placement planning not optimized for processing plant capacity.", criticality: "High" },
    { id: 157, entity: "Emirates National Foods", module: "Farm Operations", process: "DOC Placement", observation: "Biosecurity zones not enforced in placement planning.", criticality: "Medium" },
    { id: 158, entity: "Emirates National Foods", module: "Farm Operations", process: "Growing Cycle", observation: "Three feed phases: Pre-starter, Grower, Finisher. Feed changes based on age.", criticality: "High" },
    { id: 159, entity: "Emirates National Foods", module: "Farm Operations", process: "Growing Cycle", observation: "Growth curve monitoring done in Excel, not SAP.", criticality: "High" },
    { id: 160, entity: "Emirates National Foods", module: "Farm Operations", process: "Growing Cycle", observation: "Intervention decisions based on experience, not data-driven.", criticality: "Medium" },
    { id: 161, entity: "Emirates National Foods", module: "Farm Operations", process: "Feed Control", observation: "Feed delivered in bulk to farm silos. NO measurement at farm level.", criticality: "High" },
    { id: 162, entity: "Emirates National Foods", module: "Farm Operations", process: "Feed Control", observation: "Cannot verify feed delivery quantity received. GF says delivered, ENF cannot confirm.", criticality: "High" },
    { id: 163, entity: "Emirates National Foods", module: "Farm Operations", process: "Feed Control", observation: "Feed consumption per bird not accurately known.", criticality: "High" },
    { id: 164, entity: "Emirates National Foods", module: "Farm Operations", process: "FCR Performance", observation: "FCR 1.7-1.8 vs industry benchmark of 1.4. Significant opportunity for improvement.", criticality: "High" },
    { id: 165, entity: "Emirates National Foods", module: "Farm Operations", process: "FCR Performance", observation: "Cannot correlate feed quality from GF with FCR outcomes.", criticality: "High" },
    { id: 166, entity: "Emirates National Foods", module: "Farm Operations", process: "FCR Performance", observation: "FCR calculated manually in Excel using potentially inaccurate data.", criticality: "High" },
    { id: 167, entity: "Emirates National Foods", module: "Farm Operations", process: "Mortality", observation: "Mortality scrap recorded only at end of growing cycle. No daily mortality tracking.", criticality: "High" },
    { id: 168, entity: "Emirates National Foods", module: "Farm Operations", process: "Mortality", observation: "Cause of death not systematically recorded. Cannot analyze mortality trends.", criticality: "High" },
    { id: 169, entity: "Emirates National Foods", module: "Farm Operations", process: "Mortality", observation: "Financial impact of mortality not calculated in real-time.", criticality: "High" },
    { id: 170, entity: "Emirates National Foods", module: "Processing Plant", process: "Processing Facilities", observation: "Two plants: PPE for fresh Al Rawdah, FPPE for frozen Al Salwa.", criticality: "High" },
    { id: 171, entity: "Emirates National Foods", module: "Processing Plant", process: "Processing Facilities", observation: "FPPE imports 95% of raw material from Brazil. Minimal integration with local farms.", criticality: "High" },
    { id: 172, entity: "Emirates National Foods", module: "Processing Plant", process: "Processing Facilities", observation: "Plant capacity utilization not tracked systematically.", criticality: "Medium" },
    { id: 173, entity: "Emirates National Foods", module: "Processing Plant", process: "Daily Volume", observation: "50-60K birds slaughtered daily at PPE plant.", criticality: "High" },
    { id: 174, entity: "Emirates National Foods", module: "Processing Plant", process: "Daily Volume", observation: "Line speed and efficiency not captured in SAP.", criticality: "High" },
    { id: 175, entity: "Emirates National Foods", module: "Processing Plant", process: "Daily Volume", observation: "DOA (dead on arrival) birds recorded but not analyzed by transport conditions.", criticality: "Medium" },
    { id: 176, entity: "Emirates National Foods", module: "Processing Plant", process: "Production Orders", observation: "5 production orders chain: egg to DOC to broiler to carcass to finished goods.", criticality: "High" },
    { id: 177, entity: "Emirates National Foods", module: "Processing Plant", process: "Production Orders", observation: "Each stage is separate production order. No integrated tracking.", criticality: "High" },
    { id: 178, entity: "Emirates National Foods", module: "Processing Plant", process: "Production Orders", observation: "Inter-stage variances not analyzed for process improvement.", criticality: "High" },
    { id: 179, entity: "Emirates National Foods", module: "Processing Plant", process: "Carcass Split", observation: "65-70% whole birds, 30-35% portions based on demand.", criticality: "High" },
    { id: 180, entity: "Emirates National Foods", module: "Processing Plant", process: "Carcass Split", observation: "Cut-up decisions made manually, not demand-driven optimization.", criticality: "High" },
    { id: 181, entity: "Emirates National Foods", module: "Processing Plant", process: "Carcass Split", observation: "Joint product value allocation not in SAP.", criticality: "High" },
    { id: 182, entity: "Emirates National Foods", module: "Processing Plant", process: "Variable Yield", observation: "Production order created AFTER output is known. Reverse planning.", criticality: "High" },
    { id: 183, entity: "Emirates National Foods", module: "Processing Plant", process: "Variable Yield", observation: "Cannot use standard costing effectively. Actual cost only at period end.", criticality: "High" },
    { id: 184, entity: "Emirates National Foods", module: "Processing Plant", process: "Variable Yield", observation: "Yield variance analysis not systematic.", criticality: "High" },
    { id: 185, entity: "Emirates National Foods", module: "Processing Plant", process: "Catch Weight Gap", observation: "No weight-based tracking for variable weight products.", criticality: "High" },
    { id: 186, entity: "Emirates National Foods", module: "Processing Plant", process: "Catch Weight Gap", observation: "Pricing and costing based on piece count, not actual weight.", criticality: "High" },
    { id: 187, entity: "Emirates National Foods", module: "Processing Plant", process: "Catch Weight Gap", observation: "Giveaway and shortages not quantified at product level.", criticality: "High" },
    { id: 188, entity: "Emirates National Foods", module: "Materials Management", process: "Egg Procurement", observation: "Salwa is primary supplier (85%), remainder from open market imports.", criticality: "High" },
    { id: 189, entity: "Emirates National Foods", module: "Materials Management", process: "Egg Procurement", observation: "No demand-driven procurement from Salwa. Collection every 4 days regardless of need.", criticality: "High" },
    { id: 190, entity: "Emirates National Foods", module: "Materials Management", process: "Egg Procurement", observation: "Import lead time not factored into hatchery planning.", criticality: "Medium" },
    { id: 191, entity: "Emirates National Foods", module: "Materials Management", process: "Feed from GF", observation: "100% chicken feed from Greenfields (intercompany). Supply recently resumed after quality issues.", criticality: "High" },
    { id: 192, entity: "Emirates National Foods", module: "Materials Management", process: "Feed from GF", observation: "No formal SLA with GF for delivery schedule or quality.", criticality: "High" },
    { id: 193, entity: "Emirates National Foods", module: "Materials Management", process: "Feed from GF", observation: "Feed cost = 95-98% of chicken production cost. Critical supplier relationship.", criticality: "Medium" },
    { id: 194, entity: "Emirates National Foods", module: "Materials Management", process: "Feed Subsidy", observation: "90% of feed qualifies for ADS subsidy. Manual tracking and documentation.", criticality: "High" },
    { id: 195, entity: "Emirates National Foods", module: "Materials Management", process: "Feed Subsidy", observation: "Subsidy reconciliation done outside SAP. Compliance risk.", criticality: "High" },
    { id: 196, entity: "Emirates National Foods", module: "Materials Management", process: "Feed Subsidy", observation: "Quota management not integrated with procurement planning.", criticality: "Medium" },
    { id: 197, entity: "Emirates National Foods", module: "Materials Management", process: "Feed Delivery", observation: "Bulk tanker delivery to farm silos. No measurement at receiving end.", criticality: "High" },
    { id: 198, entity: "Emirates National Foods", module: "Materials Management", process: "Feed Delivery", observation: "GF delivery note vs actual receipt cannot be reconciled.", criticality: "High" },
    { id: 199, entity: "Emirates National Foods", module: "Materials Management", process: "Feed Delivery", observation: "Feed spillage and losses not tracked.", criticality: "Medium" },
    { id: 200, entity: "Emirates National Foods", module: "Materials Management", process: "Vaccine/Meds", observation: "Cold chain for vaccines and medications. Temperature compliance not in SAP.", criticality: "High" },
    { id: 201, entity: "Emirates National Foods", module: "Materials Management", process: "Vaccine/Meds", observation: "Withdrawal periods tracked manually. Compliance risk for food safety.", criticality: "High" },
    { id: 202, entity: "Emirates National Foods", module: "Materials Management", process: "Vaccine/Meds", observation: "Lot traceability for medications not linked to bird batches.", criticality: "High" },
    { id: 203, entity: "Emirates National Foods", module: "Materials Management", process: "Frozen Imports", observation: "95% of FPPE raw material imported from Brazil.", criticality: "High" },
    { id: 204, entity: "Emirates National Foods", module: "Materials Management", process: "Frozen Imports", observation: "Long lead times for imports. Frozen storage capacity constraints.", criticality: "Medium" },
    { id: 205, entity: "Emirates National Foods", module: "Quality Management", process: "Egg Quality", observation: "A/B grading for eggs newly defined. Specs being standardized.", criticality: "High" },
    { id: 206, entity: "Emirates National Foods", module: "Quality Management", process: "Egg Quality", observation: "Grading results not in SAP. Paper-based documentation.", criticality: "High" },
    { id: 207, entity: "Emirates National Foods", module: "Quality Management", process: "Egg Quality", observation: "Cannot analyze egg quality by supplier or flock age.", criticality: "Medium" },
    { id: 208, entity: "Emirates National Foods", module: "Quality Management", process: "Hatchery QC", observation: "Testing done at day 20-22 - too late to take corrective action.", criticality: "High" },
    { id: 209, entity: "Emirates National Foods", module: "Quality Management", process: "Hatchery QC", observation: "Hatchery environment parameters not logged.", criticality: "High" },
    { id: 210, entity: "Emirates National Foods", module: "Quality Management", process: "Hatchery QC", observation: "No statistical process control for hatchery operations.", criticality: "High" },
    { id: 211, entity: "Emirates National Foods", module: "Quality Management", process: "Disease Trace", observation: "Cannot trace disease origin when birds from multiple sources are mixed.", criticality: "High" },
    { id: 212, entity: "Emirates National Foods", module: "Quality Management", process: "Disease Trace", observation: "Disease outbreak response is reactive, not data-driven.", criticality: "High" },
    { id: 213, entity: "Emirates National Foods", module: "Quality Management", process: "Disease Trace", observation: "Vaccination records not linked to bird batches.", criticality: "Medium" },
    { id: 214, entity: "Emirates National Foods", module: "Quality Management", process: "In-Process QC", observation: "All quality inspection done on paper. Not in SAP QM.", criticality: "High" },
    { id: 215, entity: "Emirates National Foods", module: "Quality Management", process: "In-Process QC", observation: "HACCP control points not integrated with production orders.", criticality: "High" },
    { id: 216, entity: "Emirates National Foods", module: "Quality Management", process: "In-Process QC", observation: "Temperature monitoring at critical points not logged in system.", criticality: "Medium" },
    { id: 217, entity: "Emirates National Foods", module: "Quality Management", process: "Returns Quality", observation: "Returns inspected as good (reprocess) or bad (render).", criticality: "High" },
    { id: 218, entity: "Emirates National Foods", module: "Quality Management", process: "Returns Quality", observation: "Return reasons not analyzed for quality improvement.", criticality: "Medium" },
    { id: 219, entity: "Emirates National Foods", module: "Quality Management", process: "No LIMS", observation: "No Laboratory Information Management System. All lab work manual.", criticality: "High" },
    { id: 220, entity: "Emirates National Foods", module: "Quality Management", process: "No LIMS", observation: "Lab results not linked to production batches.", criticality: "High" },
    { id: 221, entity: "Emirates National Foods", module: "Quality Management", process: "No LIMS", observation: "Cannot analyze quality trends over time.", criticality: "High" },
    { id: 222, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Production Costing", observation: "Costing done at period level, not production order level.", criticality: "High" },
    { id: 223, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Production Costing", observation: "Cannot determine true cost of a specific batch or lot.", criticality: "High" },
    { id: 224, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Production Costing", observation: "Actual costing run monthly, not real-time.", criticality: "High" },
    { id: 225, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Joint Product", observation: "No value-based splitting for co-products (whole birds vs portions).", criticality: "High" },
    { id: 226, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Joint Product", observation: "By-product values not systematically captured (giblets, feet, etc.).", criticality: "High" },
    { id: 227, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Joint Product", observation: "Margin analysis by product type unreliable.", criticality: "Medium" },
    { id: 228, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Labor Allocation", observation: "All labor cost goes to P&L, not allocated to products.", criticality: "High" },
    { id: 229, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Labor Allocation", observation: "Cannot analyze labor cost per kg or per bird.", criticality: "High" },
    { id: 230, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Labor Allocation", observation: "Activity-based costing not implemented.", criticality: "High" },
    { id: 231, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Route Profitability", observation: "No CO-PA for route-level analysis. All van sales in one bucket.", criticality: "High" },
    { id: 232, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Route Profitability", observation: "Manual analysis required for route performance.", criticality: "High" },
    { id: 233, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Intercompany", observation: "Fixed transfer price for eggs from Salwa and feed from GF.", criticality: "High" },
    { id: 234, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Intercompany", observation: "Transfer pricing documentation not prepared for corporate tax.", criticality: "High" },
    { id: 235, entity: "Emirates National Foods", module: "Finance & Controlling", process: "Intercompany", observation: "IC reconciliation manual and time-consuming.", criticality: "High" },
    { id: 236, entity: "Emirates National Foods", module: "Finance & Controlling", process: "WIP Valuation", observation: "WIP valued at accumulated cost. No revaluation for market conditions.", criticality: "High" },
    { id: 237, entity: "Emirates National Foods", module: "Finance & Controlling", process: "WIP Valuation", observation: "Birds in farms are WIP but valuation methodology unclear.", criticality: "High" },
    { id: 238, entity: "Emirates National Foods", module: "Finance & Controlling", process: "WIP Valuation", observation: "Biological asset accounting (IAS 41) not implemented.", criticality: "Medium" },
    { id: 239, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Chicken Feed Sales", observation: "100% of chicken feed goes to ENF (intercompany).", criticality: "High" },
    { id: 240, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Chicken Feed Sales", observation: "No external customer base for chicken feed. Single customer risk.", criticality: "Medium" },
    { id: 241, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Cattle Feed Sales", observation: "Cattle feed sold to external customers. Different process.", criticality: "High" },
    { id: 242, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Cattle Feed Sales", observation: "External customer credit management separate from ENF.", criticality: "Medium" },
    { id: 243, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Gate Pass System", observation: "Custom gate pass system auto-creates sales orders.", criticality: "High" },
    { id: 244, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Gate Pass System", observation: "Weighbridge integrated with gate pass. Good control point.", criticality: "High" },
    { id: 245, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Gate Pass System", observation: "Gate pass system is custom, not standard SAP.", criticality: "Medium" },
    { id: 246, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Delivery to ENF", observation: "Direct bulk delivery to ENF farm silos.", criticality: "High" },
    { id: 247, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Delivery to ENF", observation: "No verification of quantity received at ENF farms.", criticality: "High" },
    { id: 248, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Delivery to ENF", observation: "Delivery scheduling not based on ENF farm demand.", criticality: "Medium" },
    { id: 249, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Intercompany Pricing", observation: "Fixed transfer price with margin to ENF.", criticality: "High" },
    { id: 250, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Intercompany Pricing", observation: "Price not adjusted for commodity cost changes.", criticality: "High" },
    { id: 251, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Intercompany Pricing", observation: "No formal transfer pricing policy documentation.", criticality: "High" },
    { id: 252, entity: "Greenfields for Feeds", module: "Sales & Distribution", process: "Intercompany Pricing", observation: "Margin impact on group profitability analysis limited.", criticality: "Medium" },
    { id: 253, entity: "Greenfields for Feeds", module: "Materials Management", process: "Raw Materials", observation: "Corn, cottonseed, soybean sourced globally. Commodity exposure.", criticality: "High" },
    { id: 254, entity: "Greenfields for Feeds", module: "Materials Management", process: "Raw Materials", observation: "No hedging strategy for commodity price volatility.", criticality: "Medium" },
    { id: 255, entity: "Greenfields for Feeds", module: "Materials Management", process: "No MRP in SAP", observation: "MRP not operational. All planning done in Excel.", criticality: "High" },
    { id: 256, entity: "Greenfields for Feeds", module: "Materials Management", process: "No MRP in SAP", observation: "Purchase requisitions created manually.", criticality: "High" },
    { id: 257, entity: "Greenfields for Feeds", module: "Materials Management", process: "No MRP in SAP", observation: "Lead time for grain imports (months) not in planning.", criticality: "High" },
    { id: 258, entity: "Greenfields for Feeds", module: "Materials Management", process: "Planning Horizon", observation: "Currently 1-month planning horizon. Target is 6-month.", criticality: "High" },
    { id: 259, entity: "Greenfields for Feeds", module: "Materials Management", process: "Planning Horizon", observation: "Cannot lock in commodity prices due to short horizon.", criticality: "High" },
    { id: 260, entity: "Greenfields for Feeds", module: "Materials Management", process: "Planning Horizon", observation: "Frequent expedited purchases at premium.", criticality: "Medium" },
    { id: 261, entity: "Greenfields for Feeds", module: "Materials Management", process: "No Hedging", observation: "Exposed to grain price volatility.", criticality: "High" },
    { id: 262, entity: "Greenfields for Feeds", module: "Materials Management", process: "No Hedging", observation: "Feed cost volatility passes directly to ENF chicken cost.", criticality: "High" },
    { id: 263, entity: "Greenfields for Feeds", module: "Materials Management", process: "No Hedging", observation: "No commodity risk management capability.", criticality: "High" },
    { id: 264, entity: "Greenfields for Feeds", module: "Materials Management", process: "No ENF Integration", observation: "No demand signal from ENF for feed planning.", criticality: "High" },
    { id: 265, entity: "Greenfields for Feeds", module: "Materials Management", process: "No ENF Integration", observation: "GF plans based on historical consumption, not ENF farm plan.", criticality: "Medium" },
    { id: 266, entity: "Greenfields for Feeds", module: "Production Planning", process: "Feed Formulation", observation: "External software (Easy Feed) used for formulation. Not SAP.", criticality: "High" },
    { id: 267, entity: "Greenfields for Feeds", module: "Production Planning", process: "Feed Formulation", observation: "Recipe changes not version-controlled in SAP.", criticality: "High" },
    { id: 268, entity: "Greenfields for Feeds", module: "Production Planning", process: "Feed Formulation", observation: "Formulation optimizes nutrition and cost, not inventory.", criticality: "Medium" },
    { id: 269, entity: "Greenfields for Feeds", module: "Production Planning", process: "Feed Types", observation: "Four feed types: Pre-starter, Starter, Grower, Finisher.", criticality: "High" },
    { id: 270, entity: "Greenfields for Feeds", module: "Production Planning", process: "Feed Types", observation: "Each type has ENF-specific recipes.", criticality: "Medium" },
    { id: 271, entity: "Greenfields for Feeds", module: "Production Planning", process: "Capacity Utilization", observation: "Mill utilization 35-60%. No confirmed orders from ENF.", criticality: "High" },
    { id: 272, entity: "Greenfields for Feeds", module: "Production Planning", process: "Capacity Utilization", observation: "Production based on forecast, not firm demand.", criticality: "High" },
    { id: 273, entity: "Greenfields for Feeds", module: "Production Planning", process: "Capacity Utilization", observation: "Idle capacity cost absorbed by feed price.", criticality: "High" },
    { id: 274, entity: "Greenfields for Feeds", module: "Production Planning", process: "Bulk Delivery", observation: "32.5T tanker capacity. Direct to ENF farm silos.", criticality: "High" },
    { id: 275, entity: "Greenfields for Feeds", module: "Production Planning", process: "Bulk Delivery", observation: "No verification of delivery at ENF farm.", criticality: "High" },
    { id: 276, entity: "Greenfields for Feeds", module: "Production Planning", process: "Bulk Delivery", observation: "Delivery scheduling not optimized.", criticality: "High" },
    { id: 277, entity: "Greenfields for Feeds", module: "Production Planning", process: "No Measurement", observation: "No measurement system at ENF farm silos.", criticality: "High" },
    { id: 278, entity: "Greenfields for Feeds", module: "Production Planning", process: "No Measurement", observation: "GF delivery note is only record. No receiving confirmation.", criticality: "High" },
    { id: 279, entity: "Greenfields for Feeds", module: "Production Planning", process: "No Measurement", observation: "Potential for quantity disputes.", criticality: "High" },
    { id: 280, entity: "Greenfields for Feeds", module: "Production Planning", process: "Excess = Waste", observation: "Excess feed at farm cannot be transferred. Disposed as waste.", criticality: "High" },
    { id: 281, entity: "Greenfields for Feeds", module: "Production Planning", process: "Excess = Waste", observation: "No mechanism to return unused feed.", criticality: "High" },
    { id: 282, entity: "Greenfields for Feeds", module: "Production Planning", process: "Excess = Waste", observation: "Feed waste not quantified or analyzed.", criticality: "High" },
    { id: 283, entity: "Greenfields for Feeds", module: "Quality Management", process: "Quality History", observation: "GF supply to ENF was stopped due to quality issues. Recently resumed.", criticality: "High" },
    { id: 284, entity: "Greenfields for Feeds", module: "Quality Management", process: "Quality History", observation: "Quality metrics from stoppage period not available.", criticality: "High" },
    { id: 285, entity: "Greenfields for Feeds", module: "Quality Management", process: "Quality History", observation: "No formal quality improvement plan documented.", criticality: "Medium" },
    { id: 286, entity: "Greenfields for Feeds", module: "Quality Management", process: "New Recipe Testing", observation: "New recipes tested on 2-3 ENF farms before rollout.", criticality: "High" },
    { id: 287, entity: "Greenfields for Feeds", module: "Quality Management", process: "New Recipe Testing", observation: "Trial results not systematically captured.", criticality: "High" },
    { id: 288, entity: "Greenfields for Feeds", module: "Quality Management", process: "New Recipe Testing", observation: "No controlled trial methodology.", criticality: "High" },
    { id: 289, entity: "Greenfields for Feeds", module: "Quality Management", process: "FCR Accountability", observation: "Cannot correlate feed from GF with FCR at ENF farms.", criticality: "High" },
    { id: 290, entity: "Greenfields for Feeds", module: "Quality Management", process: "FCR Accountability", observation: "Feed quality blamed but no data to verify.", criticality: "High" },
    { id: 291, entity: "Greenfields for Feeds", module: "Quality Management", process: "FCR Accountability", observation: "No shared metrics or accountability framework.", criticality: "Medium" },
    { id: 292, entity: "Greenfields for Feeds", module: "Quality Management", process: "Spec Management", observation: "Nutritional specifications maintained for ENF requirements.", criticality: "High" },
    { id: 293, entity: "Greenfields for Feeds", module: "Quality Management", process: "Spec Management", observation: "Spec changes not communicated systematically.", criticality: "Medium" },
    { id: 294, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Intercompany Price", observation: "Fixed margin pricing to ENF for chicken feed.", criticality: "High" },
    { id: 295, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Intercompany Price", observation: "Margin does not flex with commodity cost changes.", criticality: "Medium" },
    { id: 296, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Division Consolidation", observation: "GF eliminated at poultry division level for group reporting.", criticality: "High" },
    { id: 297, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Division Consolidation", observation: "IC elimination manual and time-consuming.", criticality: "Medium" },
    { id: 298, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Production Costing", observation: "Standard cost approach with period-based actual costing.", criticality: "High" },
    { id: 299, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Production Costing", observation: "No batch-level costing visibility.", criticality: "High" },
    { id: 300, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Production Costing", observation: "Commodity price changes reflected at month-end only.", criticality: "Medium" },
    { id: 301, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Commodity Exposure", observation: "No hedging for grain commodity exposure.", criticality: "High" },
    { id: 302, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Commodity Exposure", observation: "Cost volatility passes through to chicken cost.", criticality: "High" },
    { id: 303, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "Commodity Exposure", observation: "Cannot lock in feed cost for budget periods.", criticality: "Medium" },
    { id: 304, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "FCR Impact", observation: "0.1 improvement in FCR = 0.5M AED annual savings.", criticality: "High" },
    { id: 305, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "FCR Impact", observation: "FCR improvement opportunity not quantified by farm or feed type.", criticality: "High" },
    { id: 306, entity: "Greenfields for Feeds", module: "Finance & Controlling", process: "FCR Impact", observation: "No shared incentive for GF-ENF FCR improvement.", criticality: "High" },
    { id: 307, entity: "Salwa @ Liwa", module: "Production Planning", process: "DOC Sourcing", observation: "100% day-old chicks imported from Saudi Arabia. 30K x 3 batches/year.", criticality: "High" },
    { id: 308, entity: "Salwa @ Liwa", module: "Production Planning", process: "DOC Sourcing", observation: "Single country source creates supply risk.", criticality: "High" },
    { id: 309, entity: "Salwa @ Liwa", module: "Production Planning", process: "DOC Sourcing", observation: "Import timing not integrated with laying house planning.", criticality: "Medium" },
    { id: 310, entity: "Salwa @ Liwa", module: "Production Planning", process: "Rearing Cycle", observation: "0-24 week rearing cycle in 4 houses.", criticality: "High" },
    { id: 311, entity: "Salwa @ Liwa", module: "Production Planning", process: "Rearing Cycle", observation: "Rearing performance (mortality, uniformity) tracked in Excel.", criticality: "High" },
    { id: 312, entity: "Salwa @ Liwa", module: "Production Planning", process: "Rearing Cycle", observation: "Transfer to laying houses based on age, not readiness metrics.", criticality: "Medium" },
    { id: 313, entity: "Salwa @ Liwa", module: "Production Planning", process: "Laying Houses", observation: "2 farms with 8 houses total, 26K birds capacity.", criticality: "High" },
    { id: 314, entity: "Salwa @ Liwa", module: "Production Planning", process: "Laying Houses", observation: "House-level production not tracked in SAP.", criticality: "High" },
    { id: 315, entity: "Salwa @ Liwa", module: "Production Planning", process: "Laying Houses", observation: "Laying cycle management done manually.", criticality: "Medium" },
    { id: 316, entity: "Salwa @ Liwa", module: "Production Planning", process: "Production Cycle", observation: "Week 25-65 production, 41 weeks of laying.", criticality: "High" },
    { id: 317, entity: "Salwa @ Liwa", module: "Production Planning", process: "Production Cycle", observation: "Production curve vs breed standard not analyzed in system.", criticality: "High" },
    { id: 318, entity: "Salwa @ Liwa", module: "Production Planning", process: "Production Cycle", observation: "Depletion timing decision made manually.", criticality: "Medium" },
    { id: 319, entity: "Salwa @ Liwa", module: "Production Planning", process: "Daily Production", observation: "52,000 eggs per day at peak production.", criticality: "High" },
    { id: 320, entity: "Salwa @ Liwa", module: "Production Planning", process: "Daily Production", observation: "Daily production recorded on paper first, then entered to system.", criticality: "High" },
    { id: 321, entity: "Salwa @ Liwa", module: "Production Planning", process: "Daily Production", observation: "Production forecasting not in SAP.", criticality: "High" },
    { id: 322, entity: "Salwa @ Liwa", module: "Production Planning", process: "ENF Collection", observation: "ENF truck collects eggs every 4 days.", criticality: "High" },
    { id: 323, entity: "Salwa @ Liwa", module: "Production Planning", process: "ENF Collection", observation: "Collection schedule fixed, not demand-driven.", criticality: "High" },
    { id: 324, entity: "Salwa @ Liwa", module: "Production Planning", process: "ENF Collection", observation: "Egg age at collection varies, affecting hatchability.", criticality: "High" },
    { id: 325, entity: "Salwa @ Liwa", module: "Quality Management", process: "Egg Quality", observation: "A/B grading done at ENF, not at Salwa. Cannot attribute damage.", criticality: "High" },
    { id: 326, entity: "Salwa @ Liwa", module: "Quality Management", process: "Egg Quality", observation: "Egg quality not tracked by house or flock age.", criticality: "High" },
    { id: 327, entity: "Salwa @ Liwa", module: "Quality Management", process: "Egg Quality", observation: "No quality incentive in transfer pricing.", criticality: "Medium" },
    { id: 328, entity: "Salwa @ Liwa", module: "Quality Management", process: "Flock Health", observation: "Mortality and health tracking on paper. Not in SAP.", criticality: "High" },
    { id: 329, entity: "Salwa @ Liwa", module: "Quality Management", process: "Flock Health", observation: "Medication and vaccination not batch-tracked.", criticality: "High" },
    { id: 330, entity: "Salwa @ Liwa", module: "Quality Management", process: "Flock Health", observation: "Disease outbreak traceability limited.", criticality: "Medium" },
    { id: 331, entity: "Salwa @ Liwa", module: "Quality Management", process: "Grading Location", observation: "Grading done at ENF (destination) not Salwa (source).", criticality: "High" },
    { id: 332, entity: "Salwa @ Liwa", module: "Quality Management", process: "Grading Location", observation: "Transport damage not separately identified.", criticality: "High" },
    { id: 333, entity: "Salwa @ Liwa", module: "Quality Management", process: "Grading Location", observation: "Quality feedback to Salwa delayed and incomplete.", criticality: "High" },
    { id: 334, entity: "Salwa @ Liwa", module: "Quality Management", process: "Biosecurity", observation: "Strict biosecurity protocols at farms.", criticality: "High" },
    { id: 335, entity: "Salwa @ Liwa", module: "Quality Management", process: "Biosecurity", observation: "Visitor and vehicle controls manual.", criticality: "Medium" },
    { id: 336, entity: "Salwa @ Liwa", module: "Materials Management", process: "Feed Procurement", observation: "Feed supplied by GF via ENF. Indirect supply chain.", criticality: "High" },
    { id: 337, entity: "Salwa @ Liwa", module: "Materials Management", process: "Feed Procurement", observation: "Feed quantity and quality not verified at receipt.", criticality: "High" },
    { id: 338, entity: "Salwa @ Liwa", module: "Materials Management", process: "Feed Procurement", observation: "No direct relationship with GF for specifications.", criticality: "Medium" },
    { id: 339, entity: "Salwa @ Liwa", module: "Materials Management", process: "Feed Supply", observation: "GF feed via ENF using ADS subsidy quota.", criticality: "High" },
    { id: 340, entity: "Salwa @ Liwa", module: "Materials Management", process: "Feed Supply", observation: "Subsidy documentation complex due to routing.", criticality: "High" },
    { id: 341, entity: "Salwa @ Liwa", module: "Materials Management", process: "Feed Supply", observation: "Feed cost allocation to eggs unclear.", criticality: "Medium" },
    { id: 342, entity: "Salwa @ Liwa", module: "Materials Management", process: "Farm Inputs", observation: "Vaccines, medications, and supplies procured separately.", criticality: "High" },
    { id: 343, entity: "Salwa @ Liwa", module: "Materials Management", process: "Farm Inputs", observation: "No MRP for farm consumables.", criticality: "High" },
    { id: 344, entity: "Salwa @ Liwa", module: "Materials Management", process: "Farm Inputs", observation: "Reorder points manual and reactive.", criticality: "High" },
    { id: 345, entity: "Salwa @ Liwa", module: "Materials Management", process: "Egg Storage", observation: "Limited storage at Salwa. Eggs must be collected promptly.", criticality: "High" },
    { id: 346, entity: "Salwa @ Liwa", module: "Materials Management", process: "Egg Storage", observation: "No controlled storage conditions at Salwa.", criticality: "High" },
    { id: 347, entity: "Salwa @ Liwa", module: "Materials Management", process: "Consumables", observation: "Paper-based inventory for farm consumables.", criticality: "High" },
    { id: 348, entity: "Salwa @ Liwa", module: "Materials Management", process: "Consumables", observation: "No min-max controls in SAP.", criticality: "High" },
    { id: 349, entity: "Salwa @ Liwa", module: "Materials Management", process: "Consumables", observation: "Stockouts addressed through emergency purchases.", criticality: "High" },
    { id: 350, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Cost Allocation", observation: "All costs accumulated at company level. No house-level costing.", criticality: "High" },
    { id: 351, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Cost Allocation", observation: "Cost per egg not calculated systematically.", criticality: "High" },
    { id: 352, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Cost Allocation", observation: "Feed cost (largest component) allocation unclear.", criticality: "Medium" },
    { id: 353, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Biological Assets", observation: "Parent stock not valued as biological asset per IAS 41.", criticality: "High" },
    { id: 354, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Biological Assets", observation: "Flock depreciation calculated manually in Excel.", criticality: "High" },
    { id: 355, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Biological Assets", observation: "Fair value changes not recognized.", criticality: "High" },
    { id: 356, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Flock Depreciation", observation: "Manual depreciation calculation in Excel.", criticality: "High" },
    { id: 357, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Flock Depreciation", observation: "Depreciation not linked to actual bird count (mortality).", criticality: "High" },
    { id: 358, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Flock Depreciation", observation: "Accounting entries posted manually at month-end.", criticality: "Medium" },
    { id: 359, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "House-Level Costing", observation: "Cannot analyze profitability by house or flock.", criticality: "High" },
    { id: 360, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "House-Level Costing", observation: "All houses treated identically regardless of performance.", criticality: "High" },
    { id: 361, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "House-Level Costing", observation: "No variance analysis by house.", criticality: "Medium" },
    { id: 362, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Transfer Pricing", observation: "Fixed price per egg to ENF.", criticality: "High" },
    { id: 363, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Transfer Pricing", observation: "Price does not reflect cost changes.", criticality: "High" },
    { id: 364, entity: "Salwa @ Liwa", module: "Finance & Controlling", process: "Transfer Pricing", observation: "No quality-based pricing differential.", criticality: "Medium" },
    { id: 365, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Customer Base", observation: "100% sales to ENF. Single customer, intercompany only.", criticality: "High" },
    { id: 366, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Customer Base", observation: "No external sales for excess production.", criticality: "Medium" },
    { id: 367, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Intercompany Process", observation: "Sales orders and invoices processed as intercompany.", criticality: "High" },
    { id: 368, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Intercompany Process", observation: "Document flow standard but manual reconciliation.", criticality: "High" },
    { id: 369, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Intercompany Process", observation: "Settlement timing issues between entities.", criticality: "Medium" },
    { id: 370, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Delivery Process", observation: "ENF truck collects every 4 days. Salwa has no delivery capability.", criticality: "High" },
    { id: 371, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Delivery Process", observation: "Collection schedule not based on egg availability.", criticality: "High" },
    { id: 372, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Delivery Process", observation: "Transport conditions (temperature) not monitored.", criticality: "Medium" },
    { id: 373, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Egg Counting", observation: "Physical count at loading. No automated counting.", criticality: "High" },
    { id: 374, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Egg Counting", observation: "Count discrepancies resolved manually.", criticality: "High" },
    { id: 375, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Egg Counting", observation: "Breakage during loading not systematically tracked.", criticality: "Medium" },
    { id: 376, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Quality Claims", observation: "Quality issues identified at ENF after grading.", criticality: "High" },
    { id: 377, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Quality Claims", observation: "Claims process not formalized.", criticality: "High" },
    { id: 378, entity: "Salwa @ Liwa", module: "Sales & Distribution", process: "Quality Claims", observation: "No root cause analysis back to Salwa operations.", criticality: "Medium" }
];

// Initialize findings table
function initFindingsTable() {
    const tbody = document.getElementById('findingsBody');
    if (!tbody) return;

    renderFindings(findingsData);

    // Setup search
    const searchInput = document.getElementById('findingsSearch');
    if (searchInput) {
        searchInput.addEventListener('input', filterFindings);
    }

    // Setup filters
    const filterEntity = document.getElementById('filterEntity');
    const filterModule = document.getElementById('filterModule');
    const filterCriticality = document.getElementById('filterCriticality');

    if (filterEntity) filterEntity.addEventListener('change', filterFindings);
    if (filterModule) filterModule.addEventListener('change', filterFindings);
    if (filterCriticality) filterCriticality.addEventListener('change', filterFindings);
}

function renderFindings(data) {
    const tbody = document.getElementById('findingsBody');
    if (!tbody) return;

    tbody.innerHTML = data.map(f => `
        <tr class="criticality-${f.criticality.toLowerCase()}">
            <td class="col-id">${f.id}</td>
            <td class="col-entity">${f.entity}</td>
            <td class="col-module">${f.module}</td>
            <td class="col-process">${f.process}</td>
            <td class="col-observation">${f.observation}</td>
            <td class="col-criticality"><span class="badge badge-${f.criticality.toLowerCase()}">${f.criticality}</span></td>
        </tr>
    `).join('');

    // Update count
    const countEl = document.getElementById('resultsCount');
    if (countEl) {
        countEl.textContent = data.length;
    }
}

function filterFindings() {
    const searchTerm = (document.getElementById('findingsSearch')?.value || '').toLowerCase();
    const entityFilter = document.getElementById('filterEntity')?.value || '';
    const moduleFilter = document.getElementById('filterModule')?.value || '';
    const criticalityFilter = document.getElementById('filterCriticality')?.value || '';

    const filtered = findingsData.filter(f => {
        // Search filter
        const matchesSearch = !searchTerm ||
            f.observation.toLowerCase().includes(searchTerm) ||
            f.entity.toLowerCase().includes(searchTerm) ||
            f.module.toLowerCase().includes(searchTerm) ||
            f.process.toLowerCase().includes(searchTerm);

        // Dropdown filters
        const matchesEntity = !entityFilter || f.entity === entityFilter;
        const matchesModule = !moduleFilter || f.module === moduleFilter;
        const matchesCriticality = !criticalityFilter || f.criticality === criticalityFilter;

        return matchesSearch && matchesEntity && matchesModule && matchesCriticality;
    });

    renderFindings(filtered);
}

// Initialize when DOM is ready
document.addEventListener('DOMContentLoaded', initFindingsTable);
